version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_TAG: milanmahat/helloworld:latest
    docker:
      - image: docker:stable

jobs:
  test:
    working_directory: ~/circleci
    docker:
      - image: "cimg/node:16.13.2"
    steps:
      - checkout
      - run: | 
          npm install 
          npm run test

  build-push:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag "${IMAGE_TAG}" .
      - run:
          name: Push to Dockerhub
          command: |
           echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
           docker push "${IMAGE_TAG}"

  deploy:
    executor: docker-publisher
    steps:
      - run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.131.197.152 \<< EOF
          sudo docker pull "${IMAGE_TAG}"
          sudo docker container run -d -p 4200:4200 ${IMAGE_TAG} node index.js
          EOF
      
workflows:
  version: 2
  build-push:
    jobs:
      - test
      - build-push:
          requires:
            - test
          context:
            - mercantile-demo
      - deploy:
          requires:
            - build-push





## For persistant storage ##
      
      # - run:
      #     name: Archive Docker image
      #     command: docker save --output image.tar "${IMAGE_TAG}"
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - ./image.tar

## For pushing as seperate job ##
  # push:
  #   executor: docker-publisher
  #   steps:
  #     - setup_remote_docker
  #     - attach_workspace:
  #         at: /tmp/workspace
  #     - run:
  #         name: Load Docker image
  #         command: docker load --input /tmp/workspace/image.tar
  #     - run:
  #         name: Publish Docker image
  #         command: |
  #           echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
  #           docker push "${IMAGE_TAG}"
